koda/models.py
#[KODA - MODELS]

from koda import db
from sqlalchemy.schema import UniqueConstraint

class Event(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(128))
    code = db.Column(db.String(6), nullable=False, unique=True, index=True)
    alias = db.Column(db.String(32), nullable=False, unique=True, index=True)
    password = db.Column(db.String(64), nullable=False)
    two_factor = db.Column(db.String(64))
    photo_path = db.Column(db.String(128), nullable=False)

    __table_args__ = (
        UniqueConstraint('code', name='uq_event_code'),
        UniqueConstraint('alias', name='uq_event_alias')
    )

    def __repr__(self) -> str:
        return f"<Event(id={self.id}, title={self.title}, code={self.code}, alias={self.alias})>"

class Upload(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    event_alias = db.Column(db.String(32), nullable=False, index=True)
    path = db.Column(db.String(16), nullable=False)
    caption = db.Column(db.String(32))

    def __repr__(self) -> str:
        return f"<Upload(id={self.id}, event_alias={self.event_alias}, path={self.path})>"

koda/__init__.py
#[KODA - INIT]

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

import koda.config as config

db = SQLAlchemy()

def create_app() -> object:

   app = Flask(__name__)

   # Configure App Settings

   app.config['SQLALCHEMY_DATABASE_URI'] = config.DB_URI
   app.config['SECRET_KEY'] = config.SECRET
   app.config['UPLOAD_FOLDER'] = config.UPLOAD_FOLDER

   # DB Setup
   db.init_app(app)

   # Register blueprints
   from koda.blueprints import register_blueprints
   register_blueprints(app)

   # with app.app_context():
   #    db.create_all()

   return app

koda/blueprints/__init__.py
#[BLUEPRINTS - INIT]

from koda.blueprints import event, core

def register_blueprints(app):
    app.register_blueprint(event.frame, url_prefix='/event')
    app.register_blueprint(core.frame)

koda/blueprints/core.py
#[BLUEPRINTS - CORE]

from flask import Blueprint, render_template, request, redirect
from os import path
from werkzeug.utils import secure_filename
from hashlib import sha256

from koda import db
from koda.models import Event
from koda.util import *

import koda.config as config

frame:Blueprint = Blueprint('core', __name__)

@frame.route('/', methods=['GET', 'POST'])
def event_join():

    if request.method == 'POST':
        event_alias = get_join_alias_by_code(request.form['join-code'])
        if not event_alias:
            return render_template('join.html')
        return redirect('/event/{}/gallery'.format(event_alias))

    return render_template('join.html')



@frame.route('/create', methods=['GET', 'POST'])
def create():

    if request.method == 'POST':

        alias = gen_event_alias()

        print(request.files)

        if 'photo' not in request.files:
            return redirect('/create')
        
        file = request.files['photo']

        if file.filename == '':
            return redirect('/create')
        
        if file and allowed_file(file.filename):
            file_ext = file.filename.rsplit('.', 1)[1].lower()
            file_alias = filename_alias(ext=file_ext)
            file_path = path.join(config.UPLOAD_FOLDER, file_alias)
            file.save(file_path)

            new_event = Event(
                title=request.form['title'],
                description=request.form['description'],
                code=gen_event_code(),
                alias=alias,
                password='null', #sha256(request.form['password'].encode()).hexdigest(),  
                photo_path=path.join(config.UPLOAD_FOLDER.split('/koda')[-1], file_alias)
            )

            try:
                db.session.add(new_event)
                db.session.commit()
                return redirect(f'/event/{alias}/gallery')
            except Exception as e:
                db.session.rollback()
                return redirect('/create')
        else:
            return redirect('/create')


    return render_template('create.html')

@frame.route('/info')
def info():
    return render_template('info.html')

koda/blueprints/event.py
#[BLUEPRINTS - EVENT]

from flask import Blueprint, render_template, redirect, request
from os import path
from werkzeug.utils import secure_filename


import koda.config as config
from koda import db
from koda.models import Event, Upload
from koda.util import filename_alias, allowed_file

frame:Blueprint = Blueprint('event', __name__)

@frame.route('/<event_alias>/gallery', methods=['GET', 'POST'])
def event_main(event_alias:str):

    if request.method == 'POST':

        if 'photo-upload' not in request.files:
            return redirect("/event/{}/gallery".format(event_alias))
        
        file = request.files['photo-upload']

        if file.filename == '':
            return redirect("/event/{}/gallery".format(event_alias))
        
        if file and allowed_file(file.filename):
            file_ext = file.filename.rsplit('.', 1)[1].lower()
            file_alias = filename_alias(ext=file_ext)
            file_path = path.join(config.UPLOAD_FOLDER, file_alias)
            file.save(file_path)

            new_upload = Upload(
                event_alias=event_alias, 
                path=path.join(config.UPLOAD_FOLDER.split('/koda')[-1], file_alias), 
                caption=""
            )
            try:
                db.session.add(new_upload)
                db.session.commit()
            except Exception as e:
                db.session.rollback()

        return redirect(f"/event/{event_alias}/gallery")

    event_target:Event = Event.query.filter_by(alias = event_alias[:32]).first()
    if not event_target:
        return redirect('/')
    
    uploads = Upload.query.filter_by(event_alias=event_target.alias).all()[::-1]
    return render_template('event.html', event=event_target, content=uploads)

@frame.route('/<event_alias>/live')
def event_live_view(event_alias:str):
    
    event_target = Event.query.filter_by(alias=event_alias[:32]).first()
    if not event_target:
        return redirect('/')
    
    next_path = Upload.query.filter_by(event_alias=event_alias).order_by(Upload.id.desc()).first()
    if not next_path:
        return redirect(f"/event/{event_alias}/gallery")
    
    return render_template('live.html', next_path=next_path.path, event=event_target)

#@frame.route('/<event_alias>/manage')
#def event_manage(event_alias:str):
#    event_target:Event = Event.query.filter_by(alias = event_alias[:32]).first()
#    return render_template('manage.html', event=event_target)

koda/config/__init__.py
#[CONFIG - INIT]

from os import environ
from sys import modules

import koda.config.settings

APP_ENV = environ.get('APP_ENV', 'Dev')
_current = getattr(modules['koda.config.settings'], '{}Config'.format(APP_ENV))()

[
    setattr(
        modules[__name__],
        attr,
        environ.get(attr, getattr(_current, attr))
    ) for attr in [
        f for f in dir(_current) if not '__' in f
    ]
]

koda/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>{% block title %}HappyDay{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link href='https://fonts.googleapis.com/css?family=JetBrains Mono' rel='stylesheet'>
        {% block head %}{% endblock %}
    </head>
    <body>
        <div class="content-wrapper">
            {% block content %}{% endblock %}
        </div>
        {% block scripts %}{% endblock %}
    </body>
</html>

koda/templates/create.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/create.css') }}">
{% endblock %}

{% block content %}

    <div class="form-selection">
        <form method="post" enctype="multipart/form-data">
            <div class="content-select">
                <h1 class="no-select">Build Your Event!</h1>
                <input type="text" class="event-title" name="title">
                <textarea class="container event-description" maxlength="250" name="description"></textarea>
                <div class="char-counter no-select">
                    <span id="char-count">0</span>/250
                </div>
                <button type="submit" class="build-button">Start Your Event Now</button>
            </div>
            <div class="image-select">
                <img id="event-image" class="container" src="{{ url_for('static', filename='icons/image_upload_default.png') }}" alt="event-image">
                <div class="upload-icon">
                    <label for="file-input" class="photo-upload" id="file-cover"><img src="{{ url_for('static', filename='icons/image_upload_icon.png') }}"></label>
                    <input type="file" id="file-input" accept="image/*" name="photo">
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script>

        let eventPhoto = document.getElementById("event-image");
        let inputFile = document.getElementById("file-input")

        inputFile.onchange = function () {
            eventPhoto.src = URL.createObjectURL(inputFile.files[0]);
        }

        document.addEventListener('DOMContentLoaded', function () {
            const textarea = document.querySelector('.event-description');
            const char_count = document.getElementById('char-count');

            textarea.addEventListener('input', function() {
                char_count.textContent = textarea.value.length;
                if (textarea.value.length > 200){
                    char_count.style.color = "#ff5470";
                    char_count.style.textShadow = "0px 0px 2px rgba(0,0,0,0.25)"
                } else {
                    char_count.style.color = "black";
                };
            })

        })
    </script>
{% endblock %}

koda/templates/event.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/event.css') }}">
{% endblock %}

{% block content %}

    <div class="display-header">
        <img src="{{ event.photo_path }}">
        <h1>{{ event.title }}</h1>
    </div>

    <div class="active-bar">
        <button data-modal-target="#modal" class="hotbar-feature upload">Upload</button>
        <button class="hotbar-feature download-all">Download All</button>
        <a class="hotbar-feature present-wrapper" href="/event/{{ event.alias }}/live">Present</a>
        <h1 class="join-code">Code: {{ event.code }}</h1>
    </div>

    <div class="upload-gallery">
        {% for item in content %}
            <div class="media-container container">
                <img src="{{ item.path }}" alt="{{ item.caption }}">
                <h1>{{ item.caption }}</h1>
            </div>
        {% endfor %}
    </div>

    <div class="modal container" id="modal">
        <div class="modal-head">
            <h1>Upload</h1>
            <button data-close-button class="modal-close">&times;</button>
        </div>
        <form method="post" enctype=multipart/form-data>
            <img id="image-preview" src="{{ url_for('static', filename='icons/image_upload_default.png') }}" alt="image preview">
            <!--<input type="text" name="caption">-->
            <span class="upload-section">
                <label for="photo-upload" class="container">Choose Photo</label>
                <input type="file" name="photo-upload" accepts="image/*" id="photo-upload">
                <button type="submit">Submit</button>
            </span>
        </form>
    </div>
    <div id="overlay"></div>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/event.js') }}"></script>
    <script>
        let eventPhoto = document.getElementById("image-preview");
        let inputFile = document.getElementById("photo-upload")

        inputFile.onchange = function () {
            eventPhoto.src = URL.createObjectURL(inputFile.files[0]);
        }

    </script>
{% endblock %}

koda/templates/info.html
{% extends "base.html" %}

{% block content %}

    <h1>Welcome to HappyDay!</h1>
    <p>HappyDay is an evenet photoshare built to be quick and easy</p>

{% endblock %}

koda/templates/join.html
{% extends "base.html" %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block content %}


    <div class="hot-bar container">
        <h1 class="no-select">HappyDay</h1>
        <div class="hot-spacer"></div>
        <ul>
            <li><a href="#">Join</a></li>
            <li><a href="{{ url_for('core.create') }}">Create</a></li>
            <li><a href="{{ url_for('core.info') }}">Info</a></li>
        </ul>
    </div>

    <div class="main-content">
        <h1 class="no-select">JOIN THE FUN TODAY!</h1>
        <div class="form-wrap">
            <form method="post">
                <input type="text" name="join-code" spellcheck="false" autocomplete="off" maxLength="6" inputmode="numeric" pattern="[0-9]+">
                <button type="submit">Join</button>
            </form>
        </div>
    </div>

    <div class="footer">
        <div class="footer-web">
            <a href="{{ url_for('core.create') }}">Make An Event!</a>
        </div>

        <div class="footer-mobile">
            <h1 class="no-select">Make An Event!</h1>
            <h2 class="no-select">Lets start having some fun!</h2>
            <a>Get Started</a>
        </div>
    </div>


{% endblock %}

koda/templates/live.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/live.css') }}">
{% endblock %}

{% block content %}

    <div class="live-wrap">
        <img id="display-frame" src="{{ next_path }}">
        <h1>{{ event.code }}</h1>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/live.js') }}"></script>
{% endblock %}

koda/templates/manage.html
{% extends "base.html" %}

{% block content %}

    <h1>Admin Page</h1>

{% endblock %}